-- MySQL Script generated by MySQL Workbench
-- Thu Jul  4 14:44:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ritness
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ritness
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ritness` DEFAULT CHARACTER SET utf8 ;
USE `ritness` ;

-- -----------------------------------------------------
-- Table `ritness`.`workout_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ritness`.`workout_plan` (
  `id_workout_plan` INT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_workout_plan`),
  UNIQUE INDEX `id_workout_plan_UNIQUE` (`id_workout_plan` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ritness`.`workout_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ritness`.`workout_type` (
  `id_workout_type` INT NOT NULL,
  PRIMARY KEY (`id_workout_type`),
  UNIQUE INDEX `id_workout_type_UNIQUE` (`id_workout_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ritness`.`workout_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ritness`.`workout_model` (
  `id_workout_model` INT NOT NULL,
  `workout_plan_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `workout_type_id_workout_type` INT NOT NULL,
  `weekday` INT NOT NULL,
  `load` FLOAT NOT NULL,
  UNIQUE INDEX `id_workout_model_UNIQUE` (`id_workout_model` ASC),
  PRIMARY KEY (`id_workout_model`),
  INDEX `fk_workout_model_workout_plan1_idx` (`workout_plan_id` ASC),
  INDEX `fk_workout_model_workout_type1_idx` (`workout_type_id_workout_type` ASC),
  CONSTRAINT `fk_workout_model_workout_plan1`
    FOREIGN KEY (`workout_plan_id`)
    REFERENCES `ritness`.`workout_plan` (`id_workout_plan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workout_model_workout_type1`
    FOREIGN KEY (`workout_type_id_workout_type`)
    REFERENCES `ritness`.`workout_type` (`id_workout_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ritness`.`workout_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ritness`.`workout_log` (
  `id_workout_log` INT NOT NULL,
  `workout_model_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `note` VARCHAR(245) NULL DEFAULT NULL,
  `load` FLOAT NOT NULL,
  UNIQUE INDEX `id_workout_log_UNIQUE` (`id_workout_log` ASC),
  PRIMARY KEY (`id_workout_log`),
  INDEX `fk_workout_log_workout_model1_idx` (`workout_model_id` ASC),
  CONSTRAINT `fk_workout_log_workout_model1`
    FOREIGN KEY (`workout_model_id`)
    REFERENCES `ritness`.`workout_model` (`id_workout_model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ritness`.`exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ritness`.`exercise` (
  `id_exercise` INT NOT NULL,
  `name` VARCHAR(145) NOT NULL,
  `description` VARCHAR(245) NULL DEFAULT NULL,
  PRIMARY KEY (`id_exercise`),
  UNIQUE INDEX `idexercise_UNIQUE` (`id_exercise` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ritness`.`set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ritness`.`set` (
  `id_set` INT NOT NULL,
  `workout_log_id` INT NOT NULL,
  `exercise_id` INT NOT NULL,
  `weight` FLOAT NOT NULL,
  `n` INT NOT NULL,
  UNIQUE INDEX `id_set_UNIQUE` (`id_set` ASC),
  PRIMARY KEY (`id_set`),
  INDEX `fk_set_workout_log1_idx` (`workout_log_id` ASC),
  INDEX `fk_set_exercise1_idx` (`exercise_id` ASC),
  CONSTRAINT `fk_set_workout_log1`
    FOREIGN KEY (`workout_log_id`)
    REFERENCES `ritness`.`workout_log` (`id_workout_log`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_set_exercise1`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `ritness`.`exercise` (`id_exercise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
