-- MySQL Script generated by MySQL Workbench
-- Wed Jul  3 19:13:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`workout_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`workout_plan` (
  `id_workout_plan` INT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL,
  UNIQUE INDEX `id_workout_plan_UNIQUE` (`id_workout_plan` ASC) VISIBLE,
  PRIMARY KEY (`id_workout_plan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`workout_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`workout_type` (
  `id_workout_type` INT NOT NULL,
  PRIMARY KEY (`id_workout_type`),
  UNIQUE INDEX `id_workout_type_UNIQUE` (`id_workout_type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`workout_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`workout_model` (
  `id_workout_model` INT NOT NULL,
  `workout_plan_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `workout_type_id_workout_type` INT NOT NULL,
  `weekday` INT NOT NULL,
  UNIQUE INDEX `id_workout_model_UNIQUE` (`id_workout_model` ASC) VISIBLE,
  PRIMARY KEY (`id_workout_model`),
  INDEX `fk_workout_model_workout_plan1_idx` (`workout_plan_id` ASC) VISIBLE,
  INDEX `fk_workout_model_workout_type1_idx` (`workout_type_id_workout_type` ASC) VISIBLE,
  CONSTRAINT `fk_workout_model_workout_plan1`
    FOREIGN KEY (`workout_plan_id`)
    REFERENCES `mydb`.`workout_plan` (`id_workout_plan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workout_model_workout_type1`
    FOREIGN KEY (`workout_type_id_workout_type`)
    REFERENCES `mydb`.`workout_type` (`id_workout_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`workout_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`workout_log` (
  `id_workout_log` INT NOT NULL,
  `workout_model_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `note` VARCHAR(245) NULL,
  UNIQUE INDEX `id_workout_log_UNIQUE` (`id_workout_log` ASC) VISIBLE,
  PRIMARY KEY (`id_workout_log`),
  INDEX `fk_workout_log_workout_model1_idx` (`workout_model_id` ASC) VISIBLE,
  CONSTRAINT `fk_workout_log_workout_model1`
    FOREIGN KEY (`workout_model_id`)
    REFERENCES `mydb`.`workout_model` (`id_workout_model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exercise` (
  `id_exercise` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(245) NULL,
  PRIMARY KEY (`id_exercise`),
  UNIQUE INDEX `idexercise_UNIQUE` (`id_exercise` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`set` (
  `id_set` INT NOT NULL,
  `workout_log_id` INT NOT NULL,
  `exercise_id` INT NOT NULL,
  `weight` FLOAT NOT NULL,
  `n` INT NOT NULL,
  UNIQUE INDEX `id_set_UNIQUE` (`id_set` ASC) VISIBLE,
  PRIMARY KEY (`id_set`),
  INDEX `fk_set_workout_log1_idx` (`workout_log_id` ASC) VISIBLE,
  INDEX `fk_set_exercise1_idx` (`exercise_id` ASC) VISIBLE,
  CONSTRAINT `fk_set_workout_log1`
    FOREIGN KEY (`workout_log_id`)
    REFERENCES `mydb`.`workout_log` (`id_workout_log`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_set_exercise1`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `mydb`.`exercise` (`id_exercise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
